# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c83f18840c8988178c0e25596ef1e281d14779c830d28c08ffadda0b044f29837abb248f9e89a3ca4d0e0fa871ce6f39c6450f682b3a566c8db9021d979e2eaa

test:
  secret_key_base: 3139b0be4d1a6fe7c984e5234eab168f0b0570fb5aabbae705f220ccd6f60f1e59216f70b0bae2e0cd800ee7147a83532b974b65e2d773bb1b5cd9953641f51e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
